### ISSUE TITLE
Help with authentication service

### ISSUE THREAD

**Issue by ytmimi** [mdsol/mauth-client-rust#11]
Hey @masongup-mdsol, we met at the NYC rust meetup last night and you mentioned that you were having issues with the tower service you're trying to build, and I'd like to see if I can help you out!

I cloned the repo and checked out the `feature/tower-validation-service` branch. I've got things building locally, but it's a little unclear what the issue is. If you can provide me with some additional details maybe I can help figure out how to get things working!

Cheers!

**Comment by masongup-mdsol** [comment]
Hello and thanks @ytmimi.

The [new function I'm working on is here](https://github.com/mdsol/mauth-client-rust/blob/feature/tower-validation-service/src/lib.rs#L250). You'll need to build it with the feature `server` on (could probably use a better name but that works for now) in order to build that code. As the code currently is on that branch, it builds properly and can correctly validate a signed request without a body. I built [a very basic Axum server using the service to test this here](https://github.com/masongup-mdsol/test-server). The issue is in getting it to validate requests with a body.

[The currently commented-out code here](https://github.com/mdsol/mauth-client-rust/blob/feature/tower-validation-service/src/lib.rs#L283-L284) is basically what needs to be done to do this - add the bytes of the body to the hasher so that the body hash is included in the string that should match the signed string. When I uncomment that, `to_bytes` consumes the body, but I need to use [the body below here](https://github.com/mdsol/mauth-client-rust/blob/feature/tower-validation-service/src/lib.rs#L305) to generate a request to return which gets passed back down to the next Tower layer. I can of course generate a new body from that bytes data, but the problem is that I can't figure out the types resulting from that. This function needs to be generic over the body class so that the validated request can be [passed down to the next Tower layer here](https://github.com/mdsol/mauth-client-rust/blob/feature/tower-validation-service/src/tower.rs#L38). I can generate a new body of a specific type, but I can't generate a body of whatever the generic type happens to be.

If I generate a new body of a particular type, it complains that it doesn't match the generic types. I can't figure out how to set up the generics at the Service layer to allow it to pass a body of a different type down to the next service layer. Everything I've tried refuses to build here, or the built service can't be included in the [layer stack in the server here](https://github.com/masongup-mdsol/test-server/blob/master/src/main.rs#L11-L14). The generic body type doesn't support cloning or any other way to get at the bytes without consuming it. There's got to be some way for a Tower service to access the bytes of the body while still being able to pass it down to the next layer, but I can't seem to figure it out, and I haven't been able to find any examples of another Tower service/layer that does that.
